"""create_queues_table

Revision ID: 7008527f3141
Revises: 04fd8cd04701
Create Date: 2026-04-15 23:09:26.151172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7008527f3141'
down_revision: Union[str, None] = '04fd8cd04701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'IN_PROGRESS', 'DONE', name='queue_status_enum'), nullable=False),
    sa.Column('estimated_time_mins', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_index(op.f('ix_queues_doctor_id'), 'queues', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_queues_id'), 'queues', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queues_id'), table_name='queues')
    op.drop_index(op.f('ix_queues_doctor_id'), table_name='queues')
    op.drop_table('queues')
    # ### end Alembic commands ###
