"""add_auto_reassigned_to_queue

Revision ID: b333492b4300
Revises: d8d19e1bcb33
Create Date: 2026-04-17 21:24:31.885871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b333492b4300'
down_revision: Union[str, None] = 'd8d19e1bcb33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('auto_reassigned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'auto_reassigned')
    # ### end Alembic commands ###
